# Generated by Django 4.2.4 on 2023-11-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='post',
            name='isBorrow',
            field=models.BooleanField(default=False, verbose_name='外借中'),
        ),
    ]
