# Generated by Django 4.2.5 on 2023-12-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_remove_commet_pub_date_commet_pub_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commet',
            name='nickname',
            field=models.CharField(max_length=10),
        ),
    ]
