# Generated by Django 4.2.4 on 2024-01-03 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_rename_commet_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='del_pass',
        ),
    ]
