# Generated by Django 4.2.4 on 2024-01-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_remove_comment_del_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
