# Generated by Django 4.2.5 on 2024-01-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_preferences_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='male',
            new_name='gender',
        ),
    ]
